name: buscar_cep
description: "A new Flutter project."
# Prevent the package from being accidentally published to pub.dev.
publish_to: "none"

# Define version and build number.
version: 1.0.0+1

environment:
  sdk: "^3.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.9.1
  flutter_modular: ^5.0.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_multi_formatter: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.png # Caminho corrigido para a imagem

flutter_native_splash:
  color: "#FFFFFF" # Cor de fundo
  image: "lib/assets/images/logo.png" # Caminho corrigido para a imagem
  android: true
  ios: true
  android_gravity: center # Centraliza a imagem no Android
  ios_content_mode: scaleAspectFit # Ajusta a imagem proporcionalmente no iOS
  android_disable_fullscreen: true # Garante que não será cortada por fullscreen
  padding: 20px # Adiciona espaço ao redor da imagem para evitar cortes
